### ISSUE TITLE
avoid crash

### ISSUE THREAD

**Issue by TimDaub** [TimDaub/ipfs-mp4-converter#7]
```
[0] internal/child_process.js:313
[0]     throw errnoException(err, 'spawn');
[0]     ^
[0]
[0] Error: spawn ENOMEM
[0]     at ChildProcess.spawn (internal/child_process.js:313:11)
[0]     at exports.spawn (child_process.js:503:9)
[0]     at WriteStream.error (/usr/src/app/routes/index.js:79:27)
[0]     at Object.onceWrapper (events.js:313:30)
[0]     at emitNone (events.js:106:13)
[0]     at WriteStream.emit (events.js:208:7)
[0]     at fs.close (fs.js:2095:12)
[0]     at /usr/src/app/node_modules/graceful-fs/graceful-fs.js:43:10
[0]     at FSReqWrap.oncomplete (fs.js:135:15)
[0] [nodemon] app crashed - waiting for file changes before starting...
```

Node is running out of memory.

**Comment by impactcolor** [comment]
Any way to avoid this?

**Comment by TimDaub** [comment]
Hi @impactcolor, unfortunately, I never had the time to look into this. If you have a lead, please let me know!
